### ISSUE TITLE
Possible CMA issue

### ISSUE THREAD

**Issue by licaon-kter** [raspberrypi/maynard#18]
...yeah yeah I know CMA is rather not supported, if it works great if not too bad, but it worked great since it was introduced, and it's getting fixed for newer kernels too afaik

so...

RPi Model B 256Mb
Raspbian latest
Stable kernel/firmware as of April 15,  3.10.37+
CMA activated in **config.txt**:
> gpu_mem_256=112
> cma_lwm=16
> cma_hwm=32
> cma_offline_start=16

CMA activated in **cmdline.txt**:
> coherent_pool=6M

Reading http://raspberrypi.collabora.co.uk/setup-maynard.sh I've added *dispmanx_offline=1* to **config.txt** yielded this boot failure: 
![img_20140421_115739](https://cloud.githubusercontent.com/assets/2282799/2753466/1aa22bca-c935-11e3-8f93-1330b2276c34.jpg)

Sorry for the bad photo, since the RPi was my main PC these days I won't be able to edit **config.txt** for at least 2 days.

First thing I will test will be to put *gpu_mem_256=128* and if that fails too to disable CMA altogheter. So this yields at least a Wiki->FAQ entry with a warning or maybe patches/workarounds.

**Comment by fooishbar** [comment]
Unfortunately we are not able to support the Raspberry Pi graphics firmware, nor custom config options. A new, more standard, graphics driver is coming, which will make life much easier for everyone.

**Comment by licaon-kter** [comment]
This driver: https://www.raspberrypi.org/blog/another-new-raspbian-release/ ?
