### ISSUE TITLE
build-dep maynard error

### ISSUE THREAD

**Issue by ric96** [raspberrypi/maynard#23]
sudo apt-get build-dep maynard

E: Build-Depends dependency for maynard cannot be satisfied because candidate version of package libwayland-dev can't satisfy version requirements

tried: sudo apt-get install libwayland-dev #same error

**Comment by ric96** [comment]
More than 10 months and i have the same issue!!
has development halted?

pi@raspberrypi ~ $ sudo apt-get update
Get:1 http://mirrordirector.raspbian.org wheezy Release.gpg [490 B]                                  
Get:2 http://mirrordirector.raspbian.org wheezy Release [14.4 kB]                                    
Get:3 http://mirrordirector.raspbian.org wheezy/main armhf Packages [6,903 kB]                       
Hit http://archive.raspberrypi.org wheezy Release.gpg                                                
Hit http://raspberrypi.collabora.com wheezy Release.gpg                                              
Hit http://archive.raspberrypi.org wheezy Release                             
Hit http://raspberrypi.collabora.com wheezy Release                            
Hit http://archive.raspberrypi.org wheezy/main armhf Packages                  
Get:4 http://raspberrypi.collabora.com wheezy/wayland Sources [5,585 B]                         
Hit http://raspberrypi.collabora.com wheezy/rpi armhf Packages                                      
Ign http://archive.raspberrypi.org wheezy/main Translation-en_GB                                     
Ign http://archive.raspberrypi.org wheezy/main Translation-en                                        
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en_GB                                    
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en                                       
Get:5 http://mirrordirector.raspbian.org wheezy/contrib armhf Packages [23.6 kB]                     
Get:6 http://mirrordirector.raspbian.org wheezy/non-free armhf Packages [49.3 kB]                    
Get:7 http://mirrordirector.raspbian.org wheezy/rpi armhf Packages [592 B]                           
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en_GB                              
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en
Fetched 6,997 kB in 1min 15s (92.7 kB/s)
Reading package lists... Done
pi@raspberrypi ~ $ sudo apt-get build-dep maynard
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Build-Depends dependency for maynard cannot be satisfied because candidate version of package libwayland-dev can't satisfy version requirements

**Comment by fooishbar** [comment]
These older versions have now been removed.
