### ISSUE TITLE
Installed maynard on fresh Raspbian, just got black screen

### ISSUE THREAD

**Issue by hzulla** [raspberrypi/maynard#30]
Hi. I'm new to this.

- created a new raspbian sd card
- installed a non-X setup, booting to command-line only
- updated all packages to newest versions
- did as told on http://raspberrypi.collabora.co.uk/maynard.html
- logged out
- logged in
- "maynard" will result in a black screen and nothing else

**Comment by hzulla** [comment]
Yes. Was able to kill the Weston process via ssh to recover access to the tty console.

**Comment by hzulla** [comment]
Are there any logs I can provide you? I didn't find any and don't know where to look for clues.

**Comment by hzulla** [comment]
Ok, started "maynard" with output redirection. Here's the stdout of running it.

    [11:39:17.487] weston 1.4.0
                   http://wayland.freedesktop.org/
                   Bug reports to: https://bugs.freedesktop.org/enter_bug.cgi?product=Wayland&component=weston&version=1.4.0
                   Build: 1.4.0-66-gdfaf65b clients: Port simple-shm and simple-egl to xdg-shell (2014-02-07 17:01:57 -0800)
    [11:39:17.488] OS: Linux, 3.12.35+, #730 PREEMPT Fri Dec 19 18:31:24 GMT 2014, armv6l
    [11:39:17.493] Using config file '/etc/xdg/weston/weston.ini'
    [11:39:17.497] Loading module '/usr/lib/arm-linux-gnueabihf/weston/rpi-backend.so'
    [11:39:17.531] initializing Raspberry Pi backend
    [11:39:17.544] Dispmanx planes are double buffered.
    [11:39:17.547] Initializing the DispmanX compositing renderer
    [11:39:17.548] Raspberry Pi HDMI output 1920x1080 px
                   guessing 60 Hz and 96 dpi
                   orientation: normal
    [11:39:17.553] launching '/usr/lib/arm-linux-gnueabihf/weston-keyboard'
    [11:39:17.777] input device Logitech USB Receiver, /dev/input/event0 is a keyboard
    [11:39:17.779] input device Logitech USB Receiver, /dev/input/event1 is a pointer caps = relative-motion button
    [11:39:17.779] input device Logitech USB Receiver, /dev/input/event1 is a keyboard
    [11:39:17.782] Loading module '/usr/lib/arm-linux-gnueabihf/weston/desktop-shell.so'
    [11:39:17.788] Module '/usr/lib/arm-linux-gnueabihf/weston/desktop-shell.so' already loaded
    [11:39:17.799] Loading module '/usr/lib/arm-linux-gnueabihf/weston/shell-helper.so'
    [11:39:18.300] Compositor capabilities:
                   arbitrary surface rotation: no
                   screen capture uses y-flip: no
    [11:39:18.301] libwayland: using socket /run/user/pi/wayland-0
    [11:39:18.303] launching '/usr/lib/arm-linux-gnueabihf/maynard'
    
    ** (maynard:2226): WARNING **: Could not open X display
    
    ** (maynard:2226): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY
    
    ** (maynard:2226): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY
    
    ** (maynard:2226): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY
    
    ** (maynard:2226): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY
    
    ** (maynard:2226): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

**Comment by jonnylamb** [comment]
It looks like your GTK doesn't have the the Wayland GDK backend, or perhaps the `DISPLAY` environment is breaking things. Is it set?

**Comment by hzulla** [comment]
> It looks like your GTK doesn't have the the Wayland GDK backend

How do I found out if it doesn't? Here's what I have installed here, via `dpkg -l | grep libgtk`:

    ii  libgtk-3-0:armhf                      3.10.2-1+rpi9+waylandrpi1               armhf        GTK+ graphical user interface library
    ii  libgtk-3-bin                          3.10.2-1+rpi9+waylandrpi1               armhf        programs for the GTK+ graphical user interface library
    ii  libgtk-3-common                       3.10.2-1+rpi9+waylandrpi1               all          common files for the GTK+ graphical user interface library
    ii  libgtk2.0-0:armhf                     2.24.10-2                               armhf        GTK+ graphical user interface library
    ii  libgtk2.0-bin                         2.24.10-2                               armhf        programs for the GTK+ graphical user interface library
    ii  libgtk2.0-common                      2.24.10-2                               all          common files for the GTK+ graphical user interface library

looks fine to me. Or not?

> or perhaps the DISPLAY environment is breaking things. Is it set?

No, it isn't. Boot choice in `raspi-config` is `Console`, when entering `maynard` the user is `pi` on a text console tty.

**Comment by ktb83** [comment]
You're not alone. I have been having the same problem. I've tried weston and maynard on Arch Linux, Rasbian Wheezy and Jessie. I've built everything from source, multiple times. I've used pre-built packages also. Any attempt to run weston-launch results in a black/blank screen. Logs do not appear to be helpful at all:

```
Date: 2015-01-07 CST
[23:53:39.348] weston 1.6.0
               http://wayland.freedesktop.org/
               Bug reports to: https://bugs.freedesktop.org/enter_bug.cgi?product=Wayland&component=weston&version=1.6.0
               Build: 1.5.93-5-g2858cc2 configure.ac: bump version to 1.6.0 (2014-09-19 13:40:14 +0300)
[23:53:39.349] OS: Linux, 3.18.1+, #731 PREEMPT Fri Dec 19 19:16:36 GMT 2014, armv6l
[23:53:39.349] Starting with no config file.
[23:53:39.361] Loading module '/usr/lib/arm-linux-gnueabihf/weston/rpi-backend.so'
[23:53:39.418] initializing Raspberry Pi backend
[23:53:39.419] Dispmanx planes are double buffered.
[23:53:39.421] Initializing the DispmanX compositing renderer
[23:53:39.422] Raspberry Pi HDMI output 1360x768 px
               guessing 60 Hz and 96 dpi
               orientation: normal
[23:53:39.426] input device 'USB Optical Mouse', /dev/input/event0 is a pointer caps = relative-motion button
[23:53:39.428] input device 'Lite-On Technology Corp. USB Multimedia Keyboard', /dev/input/event1 is a keyboard
[23:53:39.430] input device 'Lite-On Technology Corp. USB Multimedia Keyboard', /dev/input/event2 is a keyboard
[23:53:39.430] launching '/usr/lib/weston/weston-keyboard'
[23:53:39.515] Compositor capabilities:
               arbitrary surface rotation: no
               screen capture uses y-flip: no
[23:53:39.519] Loading module '/usr/lib/arm-linux-gnueabihf/weston/desktop-shell.so'
[23:53:39.525] launching '/usr/lib/weston/weston-desktop-shell'
```

Even setting debug variables in the environment such as the following reveals absolutely nothing (there is certainly more output in the log under these conditions, but the additional output doesn't reveal any errors):
```
export MESA_DEBUG=1
export EGL_LOG_LEVEL=debug
export LIBGL_DEBUG=verbose
export WAYLAND_DEBUG=1
export SYSTEMD_LOG_LEVEL=debug
```

I wish you luck. We're all going to need it. I'll check back to see if anything positive develops.

**Comment by hzulla** [comment]
> As it is now, there are several unofficial and official postings around the internet inviting Raspberry Pi owners to try out the new desktop environments either from package or source.

Indeed, that's what made me want to try maynard. A notice that it's abandoned software would have been helpful.

**Comment by ktb83** [comment]
I do have LXQT running pretty smoothly on Arch Linux now. You could try that out in the meantime.

**Comment by amckinlay** [comment]
I too get this issue after runner `sudo apt-get upgrade`. Maynard no longer works with Raspbian..

**Comment by bjornnorman** [comment]
I get the same result, using the same procedure as hzulla reported initially, so something is broken somewhere. Would be great if someone could figure out what...

**Comment by cybear** [comment]
@jonnylamb @barisione Could you update the README with a message that this is currently NOT working? It seems to cause some disappointment for the people that try it out, find that it doesn't work and end up in this thread.

**Comment by hzulla** [comment]
I'd be much more interested to know if Maynard is a dead project or not.

**Comment by sladage** [comment]
Having the same issue. Too bad, it looked promising.

**Comment by amckinlay** [comment]
I can kill the process via ssh, but then I get weird characters when I try
to type into the TTY.

**Comment by davclark** [comment]
Still broke! Maybe LXQT is the right way to go?

**Comment by HansSanitizer** [comment]
Same issue here, too bad, was looking forward to testing it out.

**Comment by monorigabor** [comment]
Same here, hope the project is not dead!

**Comment by gld1982ltd** [comment]
Can anyone confirm that the fix for Arch Linux is the same on Raspbian? 

Add the following in the `[shell]` section of your `~/.config/weston.ini`: `client=/usr/libexec/maynard`

**Comment by skylite21** [comment]
Same here, fresh Raspbian install got blank screen :(

**Comment by PFloding** [comment]
Same here.
Raspbian Wheezy 3.18,  2015-01-31
On Rpi model 2.
-> Blank screen

gld1982ltd: I don't have a weston.ini, should I?

**Comment by gld1982ltd** [comment]
PFloding: I think you should. This is for the pc development, but I think it still applies. 

The [Maynard Wiki Page:](https://github.com/raspberrypi/maynard/wiki/Develop-on-a-computer) 

The [Arch Linux package on the AUR](https://aur.archlinux.org/packages/maynard-git/) has comments concerning the `~/.config/weston.ini`.

**Comment by fooishbar** [comment]
Yes, I can confirm. This isn't actually a Maynard issue, but an issue with the Raspberry Pi backend in general on the RPi2. I'm going to move this to a freedesktop.org bug.

**Comment by hzulla** [comment]
@fooishbar - I had this issue on an RPi Model 1, not 2.

**Comment by fooishbar** [comment]
@hzulla - Thanks, I'll check it out as soon as I can. Meant to get to it last week but ran out of time.

By the sounds of it only occurring after an upgrade, it seems it's a firmware change which has broken Weston. Ouch.

@ktb83 - Maynard/Weston on RPi only see light maintenance, but the web browser is under active and regular development, seeing regular releases. It does have some bugs which are unsolvable because newer versions of Epiphany require an upgrade to WebKit2, which is too resource-intensive to run on RPi1.

**Comment by fooishbar** [comment]
@amckinlay - Did this only start happening after you did an apt-get upgrade? How often do you upgrade?

**Comment by amckinlay** [comment]
Yes. I bought a RPI and Maynard worked. I then did an upgrade and
dist-upgrade and Maynard no longer worked.

**Comment by hzulla** [comment]
@fooishbar - I never saw a working Maynard. This bug report was written after I bought my RPi 1B+ and tried Maynard for the first time.

**Comment by fooishbar** [comment]
@amckinlay @hzulla OK, thanks.

**Comment by hzulla** [comment]
Tried again, today, using a Raspberry Pi 2.

Works now. Closing.

**Comment by SinisterSoft** [comment]
hzulla: which instructions did you follow to get this working?

**Comment by hzulla** [comment]
@SinisterSoft See first entry in this thread.
