### ISSUE TITLE
kdewallpapers necessairy?

### ISSUE THREAD

**Issue by hzulla** [raspberrypi/maynard#32]
Installing maynard on an RPi depends on kdewallpapers.

It's a giant package (114MB), takes ages to download and install.

Maybe a smaller collection of demo wallpapers could be a better choice?

**Comment by chpii** [comment]
gnome-backgrounds would be also good alternative - 15,6 MB

It's really weird IMO that this is not optional and maynard will not start at all without kdewallpapers

**Comment by hzulla** [comment]
15,6 MB is still too much. IMHO, maynard only needs one demo wallpaper to run.

**Comment by joukewitteveen** [comment]
Here is a way to drop the dependency on any wallpaper:
https://gist.github.com/joukewitteveen/3739291447c9ecae9d76
It sets the default to a solid blue color. A custom wallpaper can be used by starting weston via
```BACKGROUND=/usr/share/wallpapers/Hanami/contents/images/3872x2592.jpg weston```

**Comment by MrSchism** [comment]
@joukewitteveen That's a great solution.  Personally, I'd have gone with a black background over blue, but this is at least a solution.
