### ISSUE TITLE
Update for weston 1.7?

### ISSUE THREAD

**Issue by thx1111** [raspberrypi/maynard#33]
I get build errors, trying to build against weston 1.7:

shell-helper.c:452:1: error: conflicting types for ‘module_init’
 module_init(struct weston_compositor *ec,
 ^
In file included from shell-helper.c:25:0:
/usr/include/weston/compositor.h:1543:1: note: previous declaration of ‘module_init’ was here
 module_init(struct weston_compositor *compositor,
 ^
Makefile:574: recipe for target 'shell-helper.lo' failed

Does maynard need an update for weston 1.7?

**Comment by jonnylamb** [comment]
Good question! I will look into this soon.

**Comment by jonnylamb** [comment]
Builds fine here against Weston master and 1.7.0.

**Comment by fooishbar** [comment]
Same here.
