### ISSUE TITLE
Maynard crashes on attempting to use it as an xsession

### ISSUE THREAD

**Issue by Icekhaos** [raspberrypi/maynard#37]
What the title says. It can only be launched from an X-less shell it seems.

**Comment by fooishbar** [comment]
Maynard is not an X11 session. If you want to run it as a desktop, you can
just type 'maynard' from a virtual terminal.

**Comment by Icekhaos** [comment]
Thing is, KDE runs much in the same way, despite not using X at all. Examining the configurations, yes, this should work, but doesn't: This is a desktop environment, and I am expecting it to be selectable and login, WITHOUT having to use a virtual terminal to do the job.

**Comment by fooishbar** [comment]
Er, KDE really does use X, I guarantee you. And Maynard does not. It is not
an X11 window manager. KDE is a full X11 desktop environment, including its
window manager KWin. Please search this if you don't believe me.

**Comment by Icekhaos** [comment]
http://en.wikipedia.org/wiki/Wayland_(display_server_protocol)#Desktop_environments

Seems I went a bit ahead of myself, but I will try to hack at the xsessions file for a bit more to see if I can get Maynard to not crash.

**Comment by fooishbar** [comment]
No released version of KDE supports Wayland.

Maynard will not start from Xsession, because Xsession starts X sessions,
not Wayland sessions. What you want to do cannot and will not work.

**Comment by Icekhaos** [comment]
Unless there is some other method to add Maynard to the list of desktop environments at the login prompt. I have a subtle interest at a Debian remaster of Raspbian, and Maynard would be lovely to have for this remaster in finished form. If I can hack it to start in this manner, then I will.

**Comment by fooishbar** [comment]
There is not, no. Right now, starting it from a text console is the best
option.

**Comment by Icekhaos** [comment]
Considering that, I might just write a short and simple sh to kill X and start Maynard. Shouldn't be too difficult.

**Comment by Icekhaos** [comment]
Testing around, Raspbian's version of Weston does not accept the wayland-sessions folder. Now to track this change and make a pull request.

**Comment by Icekhaos** [comment]
And here I am, trying to compile Weston when, oops, libinput is missing and nowhere in the repository for apt-get to install. Also looks like nothing version 0.8.0 or up is available, which Weston explicitly demands.

**Comment by fooishbar** [comment]
You can also download libinput from git.

**Comment by Icekhaos** [comment]
For the RPi? Yeah, a direct step by step would be appreciated, also considered the fact that I can't report issues against that whatsoever. I found the culprit and have it fixed, but not compiled.

**Comment by fooishbar** [comment]
The generic Weston compilation guide applies to RPi too.

**Comment by Icekhaos** [comment]
Which does not include libinput as far as I saw.

**Comment by Icekhaos** [comment]
So, tried to compile libinput. No libevdev. Again, not in repository. Now, however, I find no instructions.

**Comment by fooishbar** [comment]
The libevdev homepage is the first Google result for 'libevdev', which will
tell you how to build and install it.

**Comment by Icekhaos** [comment]
It will, supposedly, except it doesn't. I've searched everywhere, even combed through the thing with Google directed at the site, and I come up empty on instructions. Only things that describe how it functions (The documentation), or a description of what it is (the page itself). The package doesn't even contain a readme for reference besides the documentation that already has proven useless before downloading.

**Comment by fooishbar** [comment]
./autogen.sh && make && sudo make install

**Comment by Icekhaos** [comment]
That's a bunch better. Now, only if there was an autogen.sh in there, but there isn't any.

**Comment by fooishbar** [comment]
http://cgit.freedesktop.org/libevdev/tree/ contains an autogen.sh. If
you're using a tarball instead of git, run ./configure instead of
autogen.sh (this is the standard method of compiling well over 99% of open
source packages).

**Comment by Icekhaos** [comment]
Oh, I tried make in the directory. Said it didn't find a makefile. Problem is, there is a makefile there. I slowly feel like giving up because of obscene errors that keep piling up but I refuse to.

**Comment by fooishbar** [comment]
You need to run configure first, like so:
./configure
make
sudo make install

**Comment by Icekhaos** [comment]
Alright. libevdev and libinput are in, but it still shoots me with "No package 'libinput' found".

**Comment by fooishbar** [comment]
This is caused by PKG_CONFIG_PATH not being set - setting this is one of
the first steps in the build instructions.

**Comment by Icekhaos** [comment]
I dropped it all in a .sh and executed it as root before building through sudo and no dice. Should I try typing it?

**Comment by Icekhaos** [comment]
Nope. Continues to turn up missing.

**Comment by Icekhaos** [comment]
And packaging failed. And stuck I am, unable to compile a Weston fix.

**Comment by Icekhaos** [comment]
I am just about to give up but here goes in hope you can help me to get this building somehow.

This is what it is spitting out: http://paste.debian.net/166967/

And here is what the .sh to set up the environment looks like: http://paste.debian.net/166969/

**Comment by Icekhaos** [comment]
I am just about to give up but here goes in hope you can help me to get this building somehow.

This is what it is spitting out: http://paste.debian.net/166967/

And here is what the .sh to set up the environment looks like: http://paste.debian.net/166969/

**Comment by Icekhaos** [comment]
I am just about to give up but here goes in hope you can help me to get this building somehow.

This is what it is spitting out: http://paste.debian.net/166967/

And here is what the .sh to set up the environment looks like: http://paste.debian.net/166969/

**Comment by Icekhaos** [comment]
I am just about to give up but here goes in hope you can help me to get this building somehow.

This is what it is spitting out: http://paste.debian.net/166967/

And here is what the .sh to set up the environment looks like: http://paste.debian.net/166969/

**Comment by fooishbar** [comment]
Did you actually install libinput/libevdev into $WLD (i.e.
/home/yourusername/local), or did it install into /usr/local? Running 'sudo
make install' in those components will output exactly where it's installing
to, and there needs to be a libinput.pc present in that path, e.g.:
  - $WLD is /home/foo/local
  - ./configure for libevdev/libinput/etc must be run with
--prefix=/home/foo/local
  - 'sudo make install' must show /home/foo/local/lib/libinput.pc being
installed
  - 'ls /home/foo/local/lib/libinput.pc' must show it present

**Comment by Icekhaos** [comment]
Whoops, sorry about the duplicates. Chromium just loves crashing on ARMv6.

**Comment by Icekhaos** [comment]
I did a sudo make && sudo make install one of those cases, and no dice, despite having previously built it as root (The Debian way). Unless you're referring to something else. I'll ls the places for you.

**Comment by fooishbar** [comment]
I wouldn't say that building as root is, or has ever been, the Debian Way, but the important thing is to look at the output of the build process in order to make sure that those files are there. Make sure that $PKG_CONFIG_PATH/lib/pkgconfig/libinput.pc exists before you go any further.

Anyway, that being said, I think I've spotted your error: exports do not propagate to host shells. Namely, if you're doing:
weston$ ./environment.sh
weston$ ./configure ...
... then the environment variables will not be set. In order to set shell variables, you must do:
weston$ eval $(cat environment.sh)
weston$ ./configure ...

It might be worth running 'echo $PKG_CONFIG_PATH' before running configure/make, in order to make sure that the environment variable is actually set.

**Comment by Icekhaos** [comment]
There is no lib directory there whatsoever.

**Comment by fooishbar** [comment]
Then I don't know where you installed libinput to, but it isn't whatever $WLD is. The --prefix argument to ./configure lets you specify an install path, which in this case would be $WLD.

**Comment by Icekhaos** [comment]
In which case it was. The eval thing only gives me errors, though.

**Comment by fooishbar** [comment]
I don't know how to be more clear: if $WLD/lib/pkgconfig/libinput.pc does not exist, then libinput is not installed to $WLD. Maybe it was installed to the old value of $WLD before you changed it, but libinput MUST be installed into the current value of $WLD in order for you to compile Weston.

At this point I would recommend following the documented installation guide much more closely, rather than improvising.

**Comment by Icekhaos** [comment]
Yeah, well. I found the libs, at /lib.

**Comment by Icekhaos** [comment]
Also, now lsing the set paths. They all are set, but the problem is, most of them excuse the set paths (which are valid) to not be directories, even when I've checked three times.

**Comment by fooishbar** [comment]
I'm afraid I don't understand what your last comment is trying to say.
