### ISSUE TITLE
can't build maynard against weston 1.9

### ISSUE THREAD

**Issue by dkzeb** [raspberrypi/maynard#41]
i could install and configure all other packages (Wayland, Weston + dependencies) but i get this:

shell-helper.c: In function 'shell_helper_move_surface':
shell-helper.c:56:43: error: expected expression before 'struct'
  view = container_of(surface->views.next, struct weston_view, surface_link);
                                           ^
shell-helper.c: In function 'configure_surface':
shell-helper.c:71:42: error: expected expression before 'struct'
  new_view = container_of(es->views.next, struct weston_view, surface_link);
                                          ^
shell-helper.c: In function 'shell_helper_add_surface_to_layer':
shell-helper.c:102:10: error: expected expression before 'struct'
          struct weston_view,
          ^
shell-helper.c: In function 'configure_panel':
shell-helper.c:120:38: error: expected expression before 'struct'
  view = container_of(es->views.next, struct weston_view, surface_link);
                                      ^
shell-helper.c: In function 'shell_helper_set_panel':
shell-helper.c:137:7: error: expected expression before 'struct'
       struct weston_view,
       ^
shell-helper.c:147:9: error: expected expression before 'struct'
         struct weston_layer,
         ^
shell-helper.c: In function 'shell_helper_slide_surface':
shell-helper.c:274:43: error: expected expression before 'struct'
  view = container_of(surface->views.next, struct weston_view, surface_link);
                                           ^
shell-helper.c: In function 'helper_destroy':
shell-helper.c:446:26: error: expected expression before 'struct'
   container_of(listener, struct shell_helper, destroy_listener);
                          ^
Makefile:563: recipe for target 'shell-helper.lo' failed
make[2]: *** [shell-helper.lo] Error 1
make[2]: Leaving directory '/home/zeb/wayland/maynard/shell'
Makefile:666: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/zeb/wayland/maynard/shell'
Makefile:476: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

when trying to run "make install" on maynard itself

Saw someone else saying they had something similar for Weston 1.7 - but idk? any ideas?

**Comment by itsjef** [comment]
I got the same error too :-1: What a shame...

**Comment by fooishbar** [comment]
Fixed now with 6dff498e, thanks for the report!
