### ISSUE TITLE
Get Packages

### ISSUE THREAD

**Issue by ZanderBrown** [raspberrypi/maynard#44]
The get packages page http://raspberrypi.collabora.co.uk/maynard.html now redirects to the GitHub wiki. Not great if that's where you started.

**Comment by fooishbar** [comment]
Removed the packages link for now. It's obviously not ideal, but it'd be better to provide them together with Weston, rather than in their own repo.

**Comment by ZanderBrown** [comment]
I get that and I don't have a problem with compiling from source but a script to install all dependences would be good as at present you have to take a trial and error approach.

**Comment by NicoHood** [comment]
Could someone then please update this page? With a clean install some more packages were required and i still got errors:
https://github.com/raspberrypi/maynard/wiki/Develop-on-a-Raspberry-Pi

**Comment by ZanderBrown** [comment]
Just tried it myself manualy installed the packages autogen required and running maynard just dies with a partly obscured error

**Comment by ZanderBrown** [comment]
Managed to get the error and it's "failing to start compositor"
