### ISSUE TITLE
Immediate crash when moving a window.

### ISSUE THREAD

**Issue by vamur** [raspberrypi/maynard#46]
Archlinux - weston 1.11.0. Attempting to move a window results in immediate crash.

> weston: src/input.c:953: weston_pointer_set_focus: Assertion `view || sx == wl_fixed_from_int(-1000000)' failed.

**Comment by ZanderBrown** [comment]
Not quite this error but after hours of trying I finally got it to compile and run then opened gedit tried to use it a little and. Back to the terminal

**Comment by vamur** [comment]
This particular issue can be fixed by adding

`grab_surface_create(desktop);`

before gtk_main()

Then adding above int main(

`
static void grab_surface_create(struct desktop *desktop)
{
  
  struct wl_surface *s;
  
  GdkWindow *gdk_window;
  struct element *curtain;

  curtain = malloc (sizeof *curtain);
  memset (curtain, 0, sizeof *curtain);

  curtain->window = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  gtk_window_set_title (GTK_WINDOW (curtain->window), "maynard2");
  gtk_window_set_decorated (GTK_WINDOW (curtain->window), FALSE);
  gtk_widget_set_size_request (curtain->window, 8192, 8192);
  gtk_widget_realize (curtain->window);

  gdk_window = gtk_widget_get_window (curtain->window);
  gdk_wayland_window_set_use_custom_surface (gdk_window);

  curtain->surface = gdk_wayland_window_get_wl_surface (gdk_window);

  desktop->curtain = curtain;

  gtk_widget_show_all (curtain->window);
  weston_desktop_shell_set_grab_surface(desktop->wshell, curtain->surface);

  
}
`

**Comment by ZanderBrown** [comment]
Have you setup a pull request?
