### ISSUE TITLE
build fails due to missing include <weston/compositor.h>

### ISSUE THREAD

**Issue by sjbronner** [raspberrypi/maynard#47]
I just tried to build maynard from https://aur.archlinux.org/packages/maynard-git/. The build process was aborted with this error being the culprit:

`shell-helper.c:25:31: fatal error: weston/compositor.h: No such file or directory`

A quick check confirmed that the file didn't exist where I expected it should in `usr/include/weston`, however a couple other files were there. I checked the git repository of weston and discovered that the file compositor.h had been removed between releases 1.11.1 and 1.12.0 (2016-09-20). In fact, the entire tree was restructured. See for yourself:

https://cgit.freedesktop.org/wayland/weston/tree/?id=1.12.0
https://cgit.freedesktop.org/wayland/weston/tree/?id=1.11.1 (`compositor.h` is in `src`)

**Comment by alive4ever** [comment]
``compositor.h`` file is moved from ``src`` to ``libweston`` directory, since ``src`` is renamed to ``libweston`` on [commit b5e3ea218b183b91e17b843b375fadd37563a1c0](https://cgit.freedesktop.org/wayland/weston/commit/libweston?id=b5e3ea218b183b91e17b843b375fadd37563a1c0)

**Comment by alive4ever** [comment]
The header files is no longer inside ``/usr/include/weston``, but inside ``/usr/include/libweston-1``

**Comment by Narrat** [comment]
And maybe it would be feasible to look what libweston offers
https://github.com/wayland-project/weston/blob/master/README#L29
So maynard isn't just a modified weston (using weston.ini and such), but a independent wm?

**Comment by ZanderBrown** [comment]
OK so building on the latest Raspbian is now broken. Switching back to `weston/compositor.h` fixes it.

Is there someway to detect his?

Any chance of Wayland on Raspbian being brought back to life?
